# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: bluegreen-test-svc
  namespace: default
spec:
  selector:
    app: bluegreen-test
    color: blue
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---

