apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: nginx-config
              mountPath: "/etc/nginx/conf.d/default.conf"
              subPath: default.conf
              readOnly: true
            - name: nginx-tls-secret
              mountPath: "/etc/nginx/ssl"
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: nginx-tls-secret
          secret:
            secretName: nginx-tls-secret

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
  type: LoadBalancer
